### ISSUE TITLE
Minecraft update to bedrock 1.14

### ISSUE THREAD

**Issue by dsd1990** [mtoensing/Docker-Minecraft-Bedrock-Server#1]
Request if there is any way to update the server to the new 1.14 bedrock update. Also how do we deploy this update while still keeping our worlds?

Thank you!

**Comment by mtoensing** [comment]
If you use a Synology NAS:

Go to registry. Search for "MarcTV" and download "Bedrock Server". Go to your container and stop it. Right mouse click and select "clear". Then wait and start the container. 

Your level will be safe if you followed my video tutorial and put the map into a folder outside of the container.
