### ISSUE TITLE
Cant connect using v1.16.201

### ISSUE THREAD

**Issue by chesterweirdo** [mtoensing/Docker-Minecraft-Bedrock-Server#12]
Hi sorry but I can’t connect using v1.16.201 on an android tablet but I can using v1.16.100

musing the same username and both on the same lan. 

Does anyone know where to look.

**Comment by mtoensing** [comment]
Works on my end on my production server. Did you use the Xbox live authentication? My guess is Mojang only support the Xbox live authentication.

**Comment by chesterweirdo** [comment]
It is using my Microsoft account. 

I thought it might be the kids account but I have used mine on both to rule out account settings. 

Would anything show in logs?

**Comment by mtoensing** [comment]
What do the logs say if you try to connect? What is the error message in the client?

**Comment by chesterweirdo** [comment]
The error on the tablet is cannot connect to server. 

On the terminal on the docket image I get nothing. Not sure where else to look.

**Comment by mtoensing** [comment]
My guess is that this has nothing to do with the update. The container can not be reached.

**Comment by chesterweirdo** [comment]
Well a re install of mine craft client has improved things. I now get it showing that I have 1 user online. However when I try and connect I get “could not connect Outdated server!”

**Comment by mtoensing** [comment]
Ok, then update the Docker container :)

**Comment by chesterweirdo** [comment]
well a restart of the docker image has not helped. looking in the logs I get 
[2021-02-03 09:01:43 INFO] Version 1.16.100.4

so looks like it is not at the latest which would make sense. I don't know how to update it however

**Comment by chesterweirdo** [comment]
Okay sorted out to upgrade and now working. Thanks for the help

**Comment by mtoensing** [comment]
Glad to hear that.
