### ISSUE TITLE
Out of date question

### ISSUE THREAD

**Issue by mcironlung** [mtoensing/Docker-Minecraft-Bedrock-Server#14]
Hey, any chance for an update for iOS v1.16.210?  I keep getting the "server is out of date" message this past week.  Thanks!

**Comment by mtoensing** [comment]
The server will update itself if you update the container. But https://www.minecraft.net/de-de/download/server/bedrock/ is still not updated.

**Comment by Feneck91** [comment]
For the moment, just updated bedrock edition to 1.16.210 but with last week try:

Is it normal that https://mcsrvstat.us/ give this response?
Could not get the server status…
Did you type the correct address? The server may also be temporarily down. Please try again later.

All ports are correctly mapped. (TCP + UDP => 19132) in Docker and in Box connected to internet.
It's working only in local network. Trying using Phantom but it's not working too.
Any way to make it work for network multiplayer? Or it should work?
Thank you.

Another thing, I use rutorrent throw VPN : https://xpenology.com/forum/topic/22164-tuto-rtorrentrutorrent-au-travers-dun-vpn-openvpn/
Update my dockers with watchtower-one make it not working.
To update 'only' minecraft server, execute command:
docker start watchtower-once Serveur-Minecraft
where Serveur-Minecraft is the name of my docker minecraft server.

**Comment by Feneck91** [comment]
> Hey, any chance for an update for iOS v1.16.210? I keep getting the "server is out of date" message this past week. Thanks!

Is it really the 1.16.210 version? I think it is 1.16.220, isn't it ?

**Comment by Feneck91** [comment]
After update with Watchtower, the docker container cannot be run, it stopped all the time, the error is:
**/bin/sh: 1: ./bedrock_server: Permission denied**

**Comment by mtoensing** [comment]
Yes, I see that too. There is something wrong with the recent update of the mojang server. I will look into it.

**Comment by Feneck91** [comment]
Great, this is the priority. For the moment all is not working as expected but you take time to make this work and have nice documentation, so I want to thank you for all the work you do.

**Comment by mtoensing** [comment]
it should work now. The last update did not work. See #15

**Comment by mtoensing** [comment]
The docker container is at 1.16.220.02. Please update
