### ISSUE TITLE
/bin/sh: 1: ./bedrock_server: Permission denied

### ISSUE THREAD

**Issue by mtoensing** [mtoensing/Docker-Minecraft-Bedrock-Server#15]
I see this problem in the logs, too. I will look into this as soon as I have some spare time.

**Comment by JackTheFragger** [comment]
> I see this problem in the logs, too. I will look into this as soon as I have some spare time.

I can confirm this issue.
![Docker](https://user-images.githubusercontent.com/75476778/113826748-d03af700-9782-11eb-867a-03ecc98b6593.png)

**Comment by mtoensing** [comment]
This is fixed in the new version

**Comment by mtoensing** [comment]
I keep this open so everyone knows this is fixed
