### ISSUE TITLE
Update your tutorial

### ISSUE THREAD

**Issue by Feneck91** [mtoensing/Docker-Minecraft-Bedrock-Server#17]
I use rutorrent throw VPN : https://xpenology.com/forum/topic/22164-tuto-rtorrentrutorrent-au-travers-dun-vpn-openvpn/
Update my dockers with watchtower-one make it not working.
To update 'only' minecraft server, execute command:
docker start watchtower-once Serveur-Minecraft
where Serveur-Minecraft is the name of my docker minecraft server.

Perharps you can explain this this into your tutorial to update only the minecraft server.

**Comment by mtoensing** [comment]
This is fixed in #15 15
