### ISSUE TITLE
Multiplayer is not working if not into the same local natwork

### ISSUE THREAD

**Issue by Feneck91** [mtoensing/Docker-Minecraft-Bedrock-Server#18]
All ports are correctly mapped. (TCP + UDP => 19132) in Docker and in Box connected to internet.
It's working only in local network. Trying using Phantom but it's not working too.
Any way to make it work for network multiplayer? Or it should work?
Thank you.

**Comment by mtoensing** [comment]
Phantom works with this docker container: https://marc.tv/phantom-ps4-xbox-minecraft-bedrock-server-spielen/

**Comment by Feneck91** [comment]
It seem's not working with the 0.5.3 phantom-windows.exe and I cannot see your server with my XBox One.
Trying with changing DNS (I think it's more simple) and do the same.
Command: phantom-windows.exe -server mc.marc.tv:19132

D:\Applications\Phantom>phantom-windows.exe -server mc.marc.tv:19132

> Starting up with remote server IP: mc.marc.tv:19132
> ←[90m11:36AM←[0m ←[32mINF←[0m Starting idle connection handler
> ←[90m11:36AM←[0m ←[32mINF←[0m Binding ping server to port 19132
> ←[90m11:36AM←[0m ←[32mINF←[0m Binding proxy server to: 0.0.0.0:55310
> ←[90m11:36AM←[0m ←[32mINF←[0m Listener starting up: 0.0.0.0:19132
> ←[90m11:36AM←[0m ←[32mINF←[0m Proxy server listening!
> ←[90m11:36AM←[0m ←[32mINF←[0m Once your console pings phantom, you should see replies below.
> ←[90m11:36AM←[0m ←[32mINF←[0m Starting 1 workers
> ←[90m11:36AM←[0m ←[32mINF←[0m Listener starting up: 0.0.0.0:55310
> ←[90m11:36AM←[0m ←[32mINF←[0m Opening connection to 85.13.128.104:19132 for new client 192.168.0.227:54978!
> ←[90m11:36AM←[0m ←[32mINF←[0m Opening connection to 85.13.128.104:19132
> ←[90m11:36AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:36AM←[0m ←[32mINF←[0m New connection from client 192.168.0.227:54978 -> 0.0.0.0:19132
> ←[90m11:36AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:36AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ...
> ... etc
> ...
> ←[90m11:37AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[31mWRN←[0m read udp 192.168.0.11:53955->85.13.128.104:19132: i/o timeout
> ←[90m11:37AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[31mWRN←[0m Server seems to be offline :(
> ←[90m11:37AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[31mWRN←[0m We'll keep trying to connect...
> ←[90m11:37AM←[0m ←[32mINF←[0m Opening connection to 85.13.128.104:19132 for new client 192.168.0.227:54978!
> ←[90m11:37AM←[0m ←[32mINF←[0m Opening connection to 85.13.128.104:19132
> ←[90m11:37AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[32mINF←[0m New connection from client 192.168.0.227:54978 -> 0.0.0.0:19132
> ←[90m11:37AM←[0m ←[32mINF←[0m Sent server offline pong to client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[32mINF←[0m Sent server offline pong to client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[32mINF←[0m Received LAN ping from client: 192.168.0.227:54978
> ←[90m11:37AM←[0m ←[32mINF←[0m Sent server offline pong to client: 192.168.0.227:54978

Should I contact my internet provider?
Problem with Windows (I Accept the firewall)
