### ISSUE TITLE
https://mcsrvstat.us/ : server could not be reached!

### ISSUE THREAD

**Issue by Feneck91** [mtoensing/Docker-Minecraft-Bedrock-Server#19]
You closed this issue with https://github.com/mtoensing/Docker-Minecraft-Bedrock-Server/issues/15 but it's not the same problem.
Now the server is working well in local, but the problem still remain.

Is it normal that https://mcsrvstat.us/ give this response? (with correct server url)
Could not get the server status…

My be it is in my side, using phantom with your server not working too, I cannot play with my XBox on your server, I didn't see it!

**Comment by mtoensing** [comment]
I think you have to forward more ports in your firewall

**Comment by Feneck91** [comment]
Forward other port in my Box or docker?
Open other port on my firewall ? Wich ports?

**Comment by mtoensing** [comment]
You need 19132 udp. And yes, it is normal

**Comment by Feneck91** [comment]
PORTS 19132 UDP + TCP are redirect from my BOX => My NAS (192.168.0.50)
PORTS 19132 UDP + TCP are redirect from mys NAS (192.168.0.50) => My Docker Minecraft Server container (config into the container)

My docker container network is in network bridge mode.

When I clic to get the status on : https://mcsrvstat.us/server/45.83.231.213
tcpdump -i ovs_eth2 port 19132
tcpdump -i ovs_eth2 udp port 19132

There is no packets captured! Like if nothing is comming from this web page.
If I try with this web site : https://check-host.net/check-ping?host=darksphinx.myds.me:19132
I have captured packets in UDP and TCP 19132 ports.

**Comment by mtoensing** [comment]
Sorry I can't help you with that. The only port the server needs is 19132 and that is open in the container both tcp and udp.
