### ISSUE TITLE
Accessing Server Properties

### ISSUE THREAD

**Issue by dsd1990** [mtoensing/Docker-Minecraft-Bedrock-Server#2]
Hello! 

First, let me state that this is not an issue but rather an oversight when I originally setup my server in docker. Is there a data folder or a mountable location that I can add to see the current server properties file that the server is using? Or is there a way to interact with the server to change tick distance / server name / max threads? 

Sorry for putting this as an issue i just dont see a way to communicate with you directly. 

Thank you for your time!

**Comment by BoxeyBee** [comment]
having similar issues.  Working on a synology.  followed the excellent video.  Poked around with Putty but for the life of me cant find where you can edit server properties.  I would also like to make my account admin but it is member.

**Comment by mtoensing** [comment]
I look into this. I heard this multiple times now and I know that my tutorials lacks this part.

**Comment by mtoensing** [comment]
I rewrote the whole readme.txt. It now includes specific directions to add server.properties and whitelist.json to your local filesystem and how to add users to the whitelist.
