### ISSUE TITLE
Cant connect using v1.16.220 - old version error

### ISSUE THREAD

**Issue by flamento** [mtoensing/Docker-Minecraft-Bedrock-Server#20]

**Comment by mtoensing** [comment]
iOS, Android, Windows? I can connect with Android but not on iOS. But that seems to be an iOS problem right now.

**Comment by flamento** [comment]
Windows and iOS. old version error.

**Comment by flamento** [comment]
now this server ... INFO] Version 1.16.210.05
iOS : 1.16.220
Windows : 1.16.220

**Comment by mtoensing** [comment]
I can now connect with the most recent version of MC on iOS and Android to the most recent version of this container.

**Comment by mtoensing** [comment]
The docker container is at 1.16.220.02. Please update
