### ISSUE TITLE
Cannot connect to world

### ISSUE THREAD

**Issue by Feneck91** [mtoensing/Docker-Minecraft-Bedrock-Server#21]
When trying to connect to the server, always the same error : "Cannot connect to world"
But in local it is working.

I already make this Issue and you close it but it still not working for me.
Now, I have found the problem and I think it can help other and you should add it into your wonderful tutorial.

Into XBox Network, my NAT was in Moderate state not OPEN like in the tutorial : https://support.xbox.com/fr-FR/help/hardware-network/connect-network/xbox-one-nat-error

So, I have found a part of the solution : https://support.xbox.com/fr-FR/help/hardware-network/connect-network/xbox-one-nat-error
For me, it was just to activate UPnP, reboot all switch and box and XBOX then test again the NAT mode.
This time it was in Open state.

I try to connect to Java server with Geyser and Floodgate, : success !!!
I try with same with your server => Fail !

Is it missing something else ? Java is very heavy, I would like a Bedrock server !

**Comment by mtoensing** [comment]
In your own network? The server opens a Port to Docker. You have to open das Port to your Network as with any other Docker container. This has nothing to do with this server. This image is pretty simple: the official mojang server in an Ubuntu environment. That’s it.

**Comment by Feneck91** [comment]
My own network, at home, my local network.

I understand, it's incredible! So simple. Box -> routing TCP+UDP 19132 -> DS1815+ and Docker routing port TCP + UDP 19132 in both side and that's all !
It don't want to work. First time UPNP was not activated into Internet box, and my XBOX and say NAT is in restricted mode. Now the NAT mode gived by XBOX is open.

Question: If I run Phantom with extenal IP (darksphinx.myds.me) should I see 2 local servers? I think I see it one time, 10 days ago.
May be a NAS protection? A block account who retry to connect to app more than 10 times.
Activates Doc protection into each network (4 for the DS1815+), but I have already try to deactivated these feature with the same effet : cannot connect.

If I could try to another Bedrock server like mine I could test it...

**Comment by Feneck91** [comment]
In Network / General / Advanced parameters =>
Desactivate:
Respond to the ARP request if the target IP address is the same as the local address configured on the inbound interface.
Enable detection of IP conflicts. 

I don't know wich option make problem but for me it's resolved!

**Comment by TimeLord-Neo** [comment]
Wow

**Comment by Feneck91** [comment]
What do you want to say?
