### ISSUE TITLE
Update documentation to reflect auto-update schedule

### ISSUE THREAD

**Issue by RDslva** [mtoensing/Docker-Minecraft-Bedrock-Server#24]
Currently, the documentation does not indicate that the docker image will auto-update every 6 hours. This can lead to impatient users wondering why the new release of Minecraft is not working on the image.

It would be great to add some text that tells users the docker image looks for a new version of Minecraft every 6 hours (or however often the process actually is), and will update itself when a new version is found.

**Comment by mtoensing** [comment]
The container does not update itself. You have to update the whole container. This is the normal process for most Docker containers.

**Comment by RDslva** [comment]
I understand that the container needs to be re downloaded and re created. 

I meant that the image on docker hub gets re created automatically, on what appears to be a 6 hour cycle. I would propose the documentation here gets updated to reflect that. 

That would help protect against events when Minecraft is updated by Mojang and impatient users are wondering when your docker image will be updated to reflect the new Minecraft version.

**Comment by mtoensing** [comment]
Ah, good point!
