### ISSUE TITLE
Could not connect: Outdated Server! message

### ISSUE THREAD

**Issue by toryn74** [mtoensing/Docker-Minecraft-Bedrock-Server#27]
Hello,
My daughter and her friends are now getting a "Could not connect: Outdated Server!" message when attempting to connect to my Synology NAS.   I see from logs the server instance is 1.17.41.01, and her iPad is showing she is using v1.18.0. 

I searched images, and see the marctv image is still reflecting a server 1.17 version on it at the moment.
Is there a path to getting back up and running that I am missing?   Will updating allow me to keep the world instance my daughter and her friends have been working in?

Thank you for your time.

**Comment by mtoensing** [comment]
Just update the container. tag "latest" is 1.18

**Comment by toryn74** [comment]
Thanks so much for the quick reply.  I just wasn't sure since it was tagged with 1.17 on it.   I grabbed the latest container, copied settings over, and now running 1.18.0.02.

I was a dorf at first, and it came back with not able to connect. . .  because the new instance I copied to, had reset the ports back to auto.   Once I corrected that, it fired backup.

Appreciate it!

**Comment by mtoensing** [comment]
Anytime. Feel free to click the sponsor button
