### ISSUE TITLE
Unable to connect after adding properties and whitelist

### ISSUE THREAD

**Issue by OmniMoss** [mtoensing/Docker-Minecraft-Bedrock-Server#28]
I followed the bedrock server setup video. When attempting to connect via the "add server" to Minecraft, I have been unable to get that to work. The server did show up on my LAN network though. I logged in successfully. 

After that, I added the properties and whitelist files. Now it does not show up on the LAN.

I'm a newb, any suggestions would be very welcome.

**Comment by bfanning337** [comment]
I, too , am also having problems.  The server appears to crash on the whitelist.  I added the server properties file and altered it and it works fine.  But I had the whitelist.json file and point it to /bedrock-server/whitelist.json I get an error in docker.  I basically copied and pasted the link from the page so I can only guess that something is not pointed correctly.

Please help

**Comment by mtoensing** [comment]
Maybe a permission problem? What is the error in Docker?

**Comment by bfanning337** [comment]
I have the error here but it looks like it’s a pathing issue.  I’m attaching a photo of the error.

**Comment by bfanning337** [comment]
Here are the photos as big as I can send via email.

**Comment by mtoensing** [comment]
It does not work this way. Please upload it on github.com here in this thread. We can't see it any other way.

**Comment by bfanning337** [comment]
here is the error and the file path I used.
![error](https://user-images.githubusercontent.com/99563501/153963041-fddddbf0-d4bd-4dd2-99e9-a2c5e099e433.JPG)
![Path](https://user-images.githubusercontent.com/99563501/153963044-b2752e84-ad0d-4c59-8811-a2a481580832.JPG)

**Comment by mtoensing** [comment]
What I said earlier: you try to mount a file as a directory. Please look a bit closer at the tutorial video

**Comment by bfanning337** [comment]
But I didn’t.  It’s clicked add file when I added the server.properties and whitelist.json.

**Comment by bfanning337** [comment]
I uninstalled it and reinstalled it and it seems to be working now.
