### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by TwistedNation** [mtoensing/Docker-Minecraft-Bedrock-Server#32]
I am using your Docker on Synology and it is always stating it is Outdated. I am using watchtower to keep it updated and I always download the latest image and restart the container, with no luck in removing the error. This Docker only seems to work on a fresh install until there is an update needed. 

I am guessing this might be a user error on my part, as you keep everything up to date quickly. Any help would be greatly appreciated, I have not been able to get it back up and running for months.

**Comment by mtoensing** [comment]
Hi, the container always uses the latest officially available and stable version. Currently, it is 1.18.31.04 and can be downloaded here: https://www.minecraft.net/en-us/download/server/bedrock Sometimes the clients get updated earlier or you use a beta client. But it is not the container's fault. It is always up-to-date and uses the latest version available and will update itself. Be patient or downgrade your client.

**Comment by TwistedNation** [comment]
I think I must have a settings wrong then. I am filling the instructions and it never updates after the initial install.

**Comment by TwistedNation** [comment]
I was able to get it to work. I think having all my worlds under one Minecraft folder, may have been causing an issue. I now have the world listed as its own folder in the docker folder and it seems to work now.
