### ISSUE TITLE
Version 1.19.0

### ISSUE THREAD

**Issue by brandonio21** [mtoensing/Docker-Minecraft-Bedrock-Server#34]
Looks like version 1.19.0 came out on June 7 (https://minecraft.fandom.com/wiki/Bedrock_Edition_1.19.0)

**Comment by mtoensing** [comment]
The docker container is at 1.19.1 ... since a few days. did you update ypur containers?

**Comment by mtoensing** [comment]
I have a container based on my image running, and I can connect locally and remotely.
