### ISSUE TITLE
error while loading shared libraries: libssl.so.1.1: cannot open shared object file

### ISSUE THREAD

**Issue by GiJaLo** [mtoensing/Docker-Minecraft-Bedrock-Server#36]
Hi,

I've just updated my Minecraft sever bedrock and it won't run anymore because of the following problem:

./bedrock_server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

Thank you for the reply

**Comment by mtoensing** [comment]
I get that too. I will fix this asap

**Comment by GiJaLo** [comment]
You rock! Thank you for the awesome image and support!

**Comment by mtoensing** [comment]
Fixed! Sorry!

**Comment by mtoensing** [comment]
This happened because of this bug https://bugs.mojang.com/browse/BDS-16913
