### ISSUE TITLE
Running Second Server

### ISSUE THREAD

**Issue by TwistedNation** [mtoensing/Docker-Minecraft-Bedrock-Server#38]
I cannot get a second server to work in Synology. I change the left side of the port settings to 21132 and setup port forwarding for the same port and it does not show up under my local LAN party tab in Xbox, only my main world using port 19132. 

Am I missing something? I have seen other users get multiple worlds going, but I’m not sure if it works on Bedrock.

**Comment by mtoensing** [comment]
Put the port number with a : behind the IP address in the Minecraft client.

**Comment by TwistedNation** [comment]
I use the local LAN party menu, the realm will just appear once the Docker container is running. Right now I can only see my main world. 
![973F0B0C-E193-4A0A-8282-38F8060E208C](https://user-images.githubusercontent.com/70878201/185224796-e187e441-2759-4059-81b9-71d0560e3716.png)

**Comment by mtoensing** [comment]
Read my comment again.

enter the ip manually like 192.168.178.1:665566

**Comment by TwistedNation** [comment]
Please read my last message. I have no option to do that for LAN party

**Comment by mtoensing** [comment]
Use the „servers“ tab

**Comment by mtoensing** [comment]
But anyway: this is not a problem or issue with the Docker Container itself.therefore: closed
