### ISSUE TITLE
cant get allow-list to work

### ISSUE THREAD

**Issue by bitofanooob** [mtoensing/Docker-Minecraft-Bedrock-Server#43]
Hi,  thank u for your service providing this docker  and keeping it up to date. 
i have a server running for some time now but keep it updated and only now we want to go over the internet and let some people in but some not. therefore i try to get the whitelist funcion working and learned that is has been replaced by allow-list.
i added allow-list=true to my server.properties and edded a allowlist.json file to the server directory and mounted it in docker on my synology but...
when i enable it in server.properties with true, the server does not start. 
it tries to start but console terminal gives back "quit correctly" when i type start or list or another command.
only when i set allow-list=false  then server starts and works fine.
the same goes for whitelist and its settings.  when i enable that  it also wont start. i cleaned up the container-settings so only allow-list is mounted but same results.\
however,  when disabled  and i give command "allowlist add playername"   it ads the playername to the list..  however......
when i remove the whitelist.json  and allowlist.json files,  it also gives back "player added to allowlist  but no list is there or apears after adding.  what am i doing wring or what can i do better to get it working?
thanks for your time.

**Comment by mtoensing** [comment]
Please watch the tutorial for installation in a synology nas and try to figure out what you can do different in your setup: https://www.youtube.com/watch?v=jbyuWkF0RNQ

**Comment by bitofanooob** [comment]
the awntser was not in the video. thanks anyway

**Comment by bigbodytad** [comment]
I finally figured out how to get the whitelist and allowlist to work. The instructional video was written before allowlist, so it only specifies how to set up whitelist.

In order for the allowlist to be read during startup, you'll need to change the server settings to point to your allowlist.json. See the picture below - note my server name may be different than yours, make sure to set the docker path as appropriate your your settings. 

![Screenshot 2024-03-02 at 10 49 43 AM](https://github.com/mtoensing/Docker-Minecraft-Bedrock-Server/assets/161959080/0f30e3b4-7e3f-403d-8e58-e220b8a982a0)
