### ISSUE TITLE
permissions.json

### ISSUE THREAD

**Issue by eMeF1** [mtoensing/Docker-Minecraft-Bedrock-Server#44]
Is there a way how to configure the default OP for specific users? I have tried creating permissions.json and mapping it as a volume but no luck. If not, is there another way how to OP users other than manually via the terminal when users log in?

Thank a lot!

**Comment by mtoensing** [comment]
Yes, just look up any tutorial about Bedrock servers. This container only provides the server but I can give no support on how to use it.

**Comment by eMeF1** [comment]
Got it, thanks a lot! I had to create an empty permissions.json file in the same location as server.properties, map the volume and then op the user via the terminal. Then the permission survive container reset.
