### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by scrooch** [mtoensing/Docker-Minecraft-Bedrock-Server#47]
I would like to have access to minecraft logs from the docker machine. It is possible?

**Comment by mtoensing** [comment]
If the server writes logs you can access them. I don’t know where they or or if they exists.

**Comment by scrooch** [comment]
Portainer show me logs:
![image](https://github.com/mtoensing/Docker-Minecraft-Bedrock-Server/assets/41049116/efb6e23e-089d-498c-8f32-3db277db8796)
Do you know where it stored?

**Comment by mtoensing** [comment]
Not sorry I don’t know that .

**Comment by scrooch** [comment]
Ok ;) thx i will search it. I'd like to take that information to show in website stats, and manage server from website like "weather clear" or "time set day"

**Comment by mtoensing** [comment]
Great. Please share if you found it and we can put it into the readme
