### ISSUE TITLE
Version 1.20.0

### ISSUE THREAD

**Issue by Macgamut** [mtoensing/Docker-Minecraft-Bedrock-Server#48]
It looks like version 1.20.0 isn't up, is this coming soon? Downloading the latest in Docker, it's 1.19.72.01 as of right now. Thanks!

**Comment by waschinski** [comment]
Same here, slightly higher version but still no 1.20.0:

`[2023-06-18 19:52:33:697 INFO] Version 1.19.83.01`

Up to date clients can no longer connect to the server.

**Comment by waschinski** [comment]
Looking at the xpath query in `getbedrockserver.sh` it should properly find the current url (https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.0.01.zip) though. I would still simplify it and just check for `data-platform="serverBedrockLinux"` instead.

**Comment by mtoensing** [comment]
The server uses 1.20 and finds the 1.20 zip. Here is an extraction from the log:

```
#15 [ 9/11] RUN /getbedrockserver.sh
#15 0.964 **** Retrieving (GET): https://www.minecraft.net/en-us/download/server/bedrock ****
#15 0.964 **** Processing: https://www.minecraft.net/en-us/download/server/bedrock ****
#15 0.967 -----------------
#15 0.967 https://minecraft.azureedge.net/bin-linux/bedrock-server-1.20.0.01.zip
#15 0.967 -----------------
#15 0.973   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#15 0.974                                  Dload  Upload   Total   Spent    Left  Speed
#15 0.974 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 35 82.5M   35 29.0M    0     0  85.6M      0 --:--:-- --:--:-- --:--:-- 85.4M
100 82.5M  100 82.5M    0     0   113M      0 --:--:-- --:--:-- --:--:--  113M
#15 DONE 1.9s

#16 [10/11] RUN unzip bedrock-server-ubuntu.zip
#16 0.056 Archive:  bedrock-server-ubuntu.zip
#16 0.058   inflating: allowlist.json          
```

**Comment by waschinski** [comment]
I just pulled the latest image from Docker Hub and it's still containing version 1.19.83.01 though. Can you please check if what is being built is also pushed to the registry?

**Comment by mtoensing** [comment]
The curious thing is that I use the server myself with Watchtower as an update mechanic and it runs in 1.20.01. I removed all tags except "latest" from Dockerhub and build it manually. Please ensure you use "Latest" and not "Preview" or "nightly"

**Comment by waschinski** [comment]
I am terribly sorry, but I must admit that I messed up my volume setup when moving it to the new server, basically mounting an old version over the latest version... So at least in my case it was a dumb user error, can't speak for OP though. Once again, sorry!

**Comment by Macgamut** [comment]
> The curious thing is that I use the server myself with Watchtower as an update mechanic and it runs in 1.20.01. I removed all tags except "latest" from Dockerhub and build it manually. Please ensure you use "Latest" and not "Preview" or "nightly"

I just updated it and it's working now! Thanks so much!
