### ISSUE TITLE
Update image manually

### ISSUE THREAD

**Issue by alvadroid** [mtoensing/Docker-Minecraft-Bedrock-Server#49]
Hello,
I seen the update instructions, but I don’t see the clear button in Container Manager. Is the reset button the same thing? If so, can you please explain to me what this does? I’m a newbie to the Synology Container Manager App. 

your instructions to update image:

Re-download the image from the docker (you mean Container Manager now correct?)
Stop the container
Clear the container
Start the container

Don’t see clear option. I’d appreciate any detailed help on how to update the image
through Container Manager manually. By the way, thank you so much for your work and time on helping other with MC Servers.

Thank you in advance,

Alva

**Comment by mtoensing** [comment]
They changed a lot. I am not sure which button is correct since I use WatchTower for this task.

**Comment by nickbouton** [comment]
@alvadroid Old thread, but I was in here looking to confirm. The new command is `reset` instead of the old `clear` option:

<img width="241" alt="image" src="https://github.com/user-attachments/assets/6ffa2416-e6ea-4226-8ef3-2231fb6af9ec">

**Comment by nickbouton** [comment]
@alvadroid Sorry to necro an old/closed thread, but I was in here looking to confirm. The new command is `reset` instead of the old `clear` option:

<img width="234" alt="image" src="https://github.com/user-attachments/assets/05460896-0d0a-4e17-8797-b32768f4e05b">
