### ISSUE TITLE
Neue Server Version

### ISSUE THREAD

**Issue by TyphoonSB** [mtoensing/Docker-Minecraft-Bedrock-Server#50]
Hallo Marc,

danke für die Bereitstellung eines Docker Containers für die Bedrock Edition auf Docker Hub.

Ich habe dazu eine Frage, seit einigen Tagen wurde im IOS Appstore die Minecraft App aktualisiert auf Version 1.20.60. 
Auf der Download Seite gibt es die Version 1.20.61.01. Der Docker Container hat jedoch nur die Version 1.20.51.01.

Ich habe irgendwo gelesen das dieser Container zweimal täglich auf geupdatet wird, was auch auf Dockerhub so aussieht, jedoch wenn ich den neuen Container herunterlade, ist keine neue Server Version includiert.

Mache ich etwas falsch? Habe ich etwas falsch verstanden?

Danke für die Rückmeldung.

Simon

**Comment by mtoensing** [comment]
Der Server wird seitens MS einfach nicht so oft aktualisiert. Sobald eine neue Version verfügbar ist, wird das Image hier aktualisert.

**Comment by mtoensing** [comment]
Das Image hier hat übrigens die neue Version: 

![Screenshot 2024-02-09 at 20 46 36](https://github.com/mtoensing/Docker-Minecraft-Bedrock-Server/assets/136737/290ae8c8-5c05-4287-a96f-8883cd7f7957)

**Comment by TyphoonSB** [comment]
![IMG_0191](https://github.com/mtoensing/Docker-Minecraft-Bedrock-Server/assets/14060152/e0430440-1de1-44d4-9b50-30315b4a5386)
![IMG_0192](https://github.com/mtoensing/Docker-Minecraft-Bedrock-Server/assets/14060152/e09e86bc-85ab-498f-83ca-91e4712c4833)


Danke für die schnelle Antwort…. jedoch scheint bei mir etwas schief zu laufen…

Ich habe noch einmal den Container gelöscht, alle Images gelöscht, und dann einen neuen Pull gemacht. Siehe Foto.

Dann einen neuen Container gestartet mit dem alten Volumen, denn Daten sollen ja behalten werden.

Wie im Container Log zu sehen ist scheint es die Version 1.20.51.01. zu sein, und der MC Client sagt das der Host zu alt ist.

Kann es sein das es etwas mit den Volumen Daten zu tun hat?

**Comment by TyphoonSB** [comment]
Es scheint als wenn ich einen neuen Conatiner erstelle mit einem neuen Volumen, dann ist es auf dem neusten Stand.
Wie ist denn die richtige Vorgehensweise um die Daten mit zu nehmen?

**Comment by mtoensing** [comment]
So mache ich das: https://marc.tv/synology-docker-container-aktualisieren-watchtower/

**Comment by TyphoonSB** [comment]
Bei mir läuft es jedoch nicht auf einem Synology ….
Die Volumen Daten sind extern auf der Maschine, und sind nach dem erstellen eines neuen Containers auch noch vorhanden….
Bin leider kein Vollprofi in Docker…. Wenn ich das richtig verstehe macht Watchtower nichts anderes…

**Comment by mtoensing** [comment]
Watchtower lauft auch unter Proxmox auf einem
LCX oder VM mit Ubuntu :)

Ich glaube, du hast den Container nicht richtig gekillt. Ich habe das deswegen immer mit watchtower gemacht
