### ISSUE TITLE
[Bedrock] Please push `latest` docker tag to `1.21`

### ISSUE THREAD

**Issue by Tastaturberuf** [mtoensing/Docker-Minecraft-Bedrock-Server#57]
Thank you.

**Comment by b2un0** [comment]
Is 1.21 stable or beta?

**Comment by Tastaturberuf** [comment]
Its out today.

**Comment by b2un0** [comment]
But it’s not stable yet
https://papermc.io/downloads/paper

And also not listed in the version api.. 
https://api.papermc.io/docs/swagger-ui/index.html?configUrl=/openapi/swagger-config

Latest is only for stable releases!

**Comment by Tastaturberuf** [comment]
Is this for bedrock too?

**Comment by b2un0** [comment]
Oh, doooh. Bedrock repo 🤣my fault 

the push comes automatically at night

**Comment by Tastaturberuf** [comment]
Sorry, was my fault. Didn't mention it.

**Comment by b2un0** [comment]
The build job is running. Should be available soon.

**Comment by Tastaturberuf** [comment]
Thank you. Where can i check the available bedrock server versions? On https://www.minecraft.net/de-de/download/server/bedrock i can download or see `01.21.0.3` and as preview `1.21.10.23`. 

Which one will be `latest`?

**Comment by b2un0** [comment]
The stable version without preview flag will be the latest.

**Comment by Tastaturberuf** [comment]
Ah i see `latest` is now `1.21.0.3`. Thank you very much, now i can update my synology :)

**Comment by b2un0** [comment]
The preview tag is always on the latest preview version from your mentioned link.

the image will be build every 12 hours automatically if some of this two versions changed.

**Comment by Tastaturberuf** [comment]
is it possible to get a notification when the lastest tag changes the version?

**Comment by b2un0** [comment]
https://containrrr.dev/watchtower/

https://containrrr.dev/watchtower/notifications/

https://containrrr.dev/watchtower/container-selection/ (Monitor Only)

**Comment by Tastaturberuf** [comment]
Thank you, but thats too complicated for me. 🙈
