### ISSUE TITLE
Update to 1.16.20.03

### ISSUE THREAD

**Issue by nickbouton** [mtoensing/Docker-Minecraft-Bedrock-Server#6]
Hi @mtoensing, just a heads up that [there is a new server version out](https://minecraft.gamepedia.com/Bedrock_Edition_1.16.20). The current `marctv/minecraft-bedrock-server:latest` appears to be out of sync with the Xbox version right now.

**Comment by m00tz** [comment]
Update your server, stop the server , clear the server , restart it.

**Comment by nickbouton** [comment]
@m00tz Yeah, tried that earlier twice and it was still on the old version. Looks like the one [from 2 hours ago](d00c030) is current.

**Comment by Antotabo** [comment]
Hi, Thanks for that image good sir.  How do I update the server to latest ?

**Comment by m00tz** [comment]
> Hi, Thanks for that image good sir. How do I update the server to latest ?

Open the docker app on DSM (SynologyOS)
Go to "Registry". Search for "MarcTV" and choose the Bedrock version of Minecraft
Download the Image and wait for it to complete the download! 
Stop your running existing  container
Right click on it. Choose action and then clear.
Wait 10 seconds.
Restart the container. 
Done.
