### ISSUE TITLE
activate operator functions

### ISSUE THREAD

**Issue by EmmanuelPerezt** [mtoensing/Docker-Minecraft-Bedrock-Server#60]
i can't activate show cordenades option, writing  showcoordinates=true on server.properties and restart and not view changes in the configuration,how i can change those options or become operator ?

**Comment by b2un0** [comment]
For the last one: read the README.

**Comment by EmmanuelPerezt** [comment]
this is my permission.json
`[
  {
    "xuid": "2535459723167817",
    "permission": "operator"
  }
]`
and this is my allowlist.json
`[
  {
    "ignoresPlayerLimit": true,
    "name": "emmanuel13223",
    "xuid": "2535459723167817"
  }
]`

visually are work, but i cant activate or disable options

![Imagen de WhatsApp 2024-08-10 a las 10 07 58_a89ca291](https://github.com/user-attachments/assets/49ad27b3-44b2-4a5b-9650-19ff8001899e)

**Comment by b2un0** [comment]
Please also provide your docker run command

**Comment by EmmanuelPerezt** [comment]
using docker-compose  

```python
services:
  minecraft-bedrock:
    image: itzg/minecraft-bedrock-server:latest
    container_name: minecraft-bedrock
    ports:
      - "19132:19132/udp"
    volumes:
      - "./data:/data"
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
    stdin_open: true
    tty: true

**Comment by b2un0** [comment]
That’s not our docker container!

Here you go 

https://github.com/itzg/docker-minecraft-server
