### ISSUE TITLE
Can’t Locate Server

### ISSUE THREAD

**Issue by TwistedNation** [mtoensing/Docker-Minecraft-Bedrock-Server#7]
The Docker works great until I replace the initial install with my old world save. As soon as I override the world, the server loses ping and I cannot invite others. Is this an error with the docker or a file issue?

**Comment by mtoensing** [comment]
Stop the server. Check if the old and new world have both the same version. Copy files. Start server.

**Comment by TwistedNation** [comment]
They are not the same version. Is there a way to upgrade the version of the old world to correct this error?

**Comment by mtoensing** [comment]
Where does that old world save come from? Java or Bedrock? If it is Java, find a tutorial on how to convert the world.

**Comment by TwistedNation** [comment]
It is a Bedrock edition. I couldn't find any articles on how to force a version upgrade on an old world save.

**Comment by TwistedNation** [comment]
I was able to get it up and running and it is now pinging. I am now unable to OP my gamer tag, so not sure why this error is occurring?

Syntax error: Unexpected "first name of gamer tag": at "p first name>>second name<<

**Comment by TwistedNation** [comment]
Is operator status needed to invite others to the server? I have setup port forwarding and my ping is now working, but users do not receive invites and if I provide my credentials, they cannot join my world. Any help would be greatly appreciated.

**Comment by mtoensing** [comment]
It works on my end. I add people to the whitelist and don't invite them. Maybe that helps. But since this are not problems with the server or the container but Minecraft Bedrock in general I will close this issue.
