### ISSUE TITLE
No longer up-to-date....

### ISSUE THREAD

**Issue by mihauOne87** [mtoensing/Docker-Minecraft-Bedrock-Server#8]
Can you update to 1.16.5 ?

**Comment by mtoensing** [comment]
It will update automatically eventually.

**Comment by mihauOne87** [comment]
Ok.... 1.16.4.02. ist the leatest but not working on iOS

**Comment by mtoensing** [comment]
bedrock-server-1.16.40.02 is the latest server available https://www.minecraft.net/en-us/download/server/bedrock and it works with the latest Phone Bedrock version.
